### ISSUE TITLE
How to start with LESS

### ISSUE THREAD

**Issue by InSasquatchCountry** [10xLaCroixDrinker/zen-garden#1]
I'm just getting started with HTML and CSS. I stumbled upon your template and have been playing with it on my page[ insasquatchcountry.github.io]( insasquatchcountry.github.io). 

I did a fair amount of playing around before I saw the link to your repo.

Would you by chance be able to point me to any resources related to getting started with {less}? 

Thanks!

**Comment by 10xLaCroixDrinker** [comment]
The less docs are a great place to get started http://lesscss.org/

However, I would recommend you look as Sass https://sass-lang.com/
